export const SITE = {
  website: "https://mingcy.cn/",
  author: "茗辰原",
  profile: process.env.PUBLIC_SOCIAL_GITHUB ?? "",
  desc: "茶香四溢,编程世界.",
  title: "茗辰原",
  blogPathPrefix: "",
  ogImage: "mingcy-og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: true,
  showGalleriesInIndex: false,
  showBackButton: true,
  showTagsInCards: true,
  showCoverImages: true,
  indexPostsGrid: false,
  heroTerminalPrompt: {
    prefix: "茗",
    path: "/cheng-yuan",
    suffix: "$",
  },
  backdropEffects: {
    cursorGlow: true,
    grain: true,
  },
  editPost: {
    enabled: false,
    text: "编辑此文章",
    url: process.env.PUBLIC_EDIT_POST_URL ?? "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
  introAudio: {
    enabled: false,
    src: "",
    isStream: false,
    label: "",
    duration: 0,
  },
} as const;
